name: narendra-ci

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
  issue_comment:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: NarendraSG/github-action-workflows/.github/workflows/nodejs-ci.yml@master # if you want alternatively pin to tag version version
    with:
      package_manager: npm
      build_command: echo "build..."
      lint_command: echo "lint..."
      dev_test_branch: main
      run_dev_test: true
    secrets: inherit
